// Code generated by protoc-gen-simple-rpc. DO NOT EDIT.

package proto

import (
	context "context"
	client "github.com/hankeyyh/a-simple-rpc/client"
	protocol "github.com/hankeyyh/a-simple-rpc/protocol"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type Arith interface {
	Mul(ctx context.Context, args *Args, reply *Reply) (err error)
}

// ================== client stub ===================
// Arith is a client wrapped XClient.
type ArithClient struct {
	xclient client.XClient
}

// NewArithClient wraps a XClient as ArithClient.
// You can pass a shared XClient object created by NewXClientForArith.
func NewArithClient(xclient client.XClient) *ArithClient {
	return &ArithClient{xclient: xclient}
}

// NewXClientForArith creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForArith(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("Arith", client.FailTry, client.RoundRobin, d, opt)

	return xclient, nil
}

func (c *ArithClient) Mul(ctx context.Context, args *Args) (reply *Reply, err error) {
	reply = &Reply{}
	err = c.xclient.Call(ctx, "Mul", args, reply)
	return reply, err
}
