// Code generated by protoc-gen-simple-rpc. DO NOT EDIT.

package proto

import (
	context "context"
	client "github.com/hankeyyh/a-simple-rpc/client"
	protocol "github.com/hankeyyh/a-simple-rpc/protocol"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type Arith interface {
	Mul(ctx context.Context, args *Args, reply *Reply) (err error)
}
